### ISSUE TITLE
CKEditor: Uses malformed URLs

### ISSUE THREAD

**Issue by OBreidenbach** [primefaces-extensions/primefaces-extensions#361]
**Describe the bug**
On trying to load additional ressources  wrong urls are used.

**Environment:**
 - PF Version: _10.0_
 - JSF + version: _Mojarra 2.3.14.SP02_
 - Affected browsers: Firefox, Chrome, probably all
 
**To Reproduce**
1. Go to the showcase: https://www.primefaces.org/showcase-ext/sections/ckEditor/basicUsage.jsf
2. Start developer tools - network
3. Reload the side with Ctrl+F5
4. See gets to:
    1. https://www.primefaces.org/showcase-ext/javax.faces.resource/ckeditor/plugins/tableselection/.jsf?ln=primefaces-extensions&v=10.0.0styles/tableselection.css
    2.  https://www.primefaces.org/showcase-ext/javax.faces.resource/ckeditor/plugins/dialog/.jsf?ln=primefaces-extensions&v=10.0.0styles/dialog.css
    3. https://www.primefaces.org/showcase-ext/javax.faces.resource/ckeditor/plugins/copyformatting/.jsf?ln=primefaces-extensions&v=10.0.0styles/copyformatting.css
5. Gets should go to:  
    1. https://www.primefaces.org/showcase-ext/javax.faces.resource/ckeditor/plugins/tableselection/styles/tableselection.css.jsf?ln=primefaces-extensions&v=10.0.0
    2.  https://www.primefaces.org/showcase-ext/javax.faces.resource/ckeditor/plugins/dialog/styles/dialog.css.jsf?ln=primefaces-extensions&v=10.0.0
    3. https://www.primefaces.org/showcase-ext/javax.faces.resource/ckeditor/plugins/copyformatting/styles/copyformatting.css.jsf?ln=primefaces-extensions&v=10.0.0

We have set the responce header X-Content-Type-Options="nosniff". So I get errors in the browser console.

Only out of curiosity: With my local application I see the &e=10.0.0 parameter on every request. The showcases uses most of the time only v=10.0.0 without e=10.0.0. I did not understand what the reason for this different.

**Comment by melloware** [comment]
i will take a look

**Comment by melloware** [comment]
Ahh its weird that they give 200OK with response content empty.  I would have expected 404's?

**Comment by melloware** [comment]
Thanks for reporting this is fixed for 10.0.1

**Comment by OBreidenbach** [comment]
@melloware Thank you for the fast fix. Is there already a timetable for 10.0.1?

**Comment by melloware** [comment]
I can probably do 10.0.1 anytime.  @jepsar is there anything else you want to get in to 10.0.1?

**Comment by jepsar** [comment]
> I can probably do 10.0.1 anytime. @jepsar is there anything else you want to get in to 10.0.1?

Small change in the light switch js.. coming up

**Comment by OBreidenbach** [comment]
@melloware Do not hurry with a new release because of me. 

I did copy the new ckeditor.js and smiley.js to my application. The failure with styles/dialog.css is gone. But I still get the failures for 
* styles/tableselection.css
* styles/copyformatting.css

Is there anything else I have to do?

**Comment by OBreidenbach** [comment]
I did some digging. 
The hrefs inside the iframe are correct, for instance: .../javax.faces.resource/ckeditor/plugins/copyformatting/styles/copyformatting.css?ln=primefaces-extensions&v=10.0.0&e=10.0.0
But the CSS files are also included to the surrounding side. There the href is wrong: .../javax.faces.resource/ckeditor/plugins/copyformatting/?ln=primefaces-extensions&v=10.0.0&e=10.0.0styles/copyformatting.css.

**Comment by OBreidenbach** [comment]
There are another two references that do not use CKEDITOR.getURL on lines 862, 863 and 1294, 1295. These are splitt by a line break so the RegExp in the RessourceModifier does not match.
@melloware Thanks again for the fast fix.

**Comment by melloware** [comment]
Ahhh OK I have had to fix that resource modifier before.  Let me look.

**Comment by melloware** [comment]
OK now its really fixed.  Both those URL's are now resolving.

**Comment by OBreidenbach** [comment]
@melloware I know, I did say you do not need to hurry because of me. But meanwhile I would appreciate a 10.0.1 release of primefaces-extension. Could you do a new release during the next week or so?

**Comment by jepsar** [comment]
I would wait for https://github.com/primefaces-extensions/primefaces-extensions/issues/372 and then do a release

**Comment by OBreidenbach** [comment]
Thanks, that's very nice.

**Comment by melloware** [comment]
Yep right after @blutorange fixes the Monaco editor destroy issue i will push a 10.0.1 release.

**Comment by melloware** [comment]
@OBreidenbach 10.0.1 is now in Maven Central.

**Comment by OBreidenbach** [comment]
Thank you.
